spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graphql?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: graphql
    password: graphql
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 10000
      connection-test-query: select 1
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379

